# Uncomment this line to define a global platform for your project

platform :ios, '8.3'

# Uncomment this line if you're using Swift

use_frameworks!

pod 'SnapKit'
pod 'IMProcessing', :path => '../../'

target 'IMProcessingiOS' do
end


post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['DYLIB_COMPATIBILITY_VERSION'] = ''
            config.build_settings['ENABLE_BITCODE'] = 'NO'
        end
    end
end
