# Uncomment this line to define a global platform for your project

platform :ios, '8.3'

# Uncomment this line if you're using Swift

use_frameworks!

target 'IMProcessingiOS' do
    pod 'IMProcessing', :path => '../../'
end

