# Uncomment this line to define a global platform for your project

platform :osx, '10.11'
#platform :ios, '8.0'

# Uncomment this line if you're using Swift

use_frameworks!

pod 'SnapKit'
pod 'IMProcessing', :path => '../../'

target 'IMPGeometryTest' do
    #    pod 'IMProcessing', :path => '../../'
end

target 'IMPGeometryTestiOS' do
    #    pod 'IMProcessing', :path => '../../'
end


post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['DYLIB_COMPATIBILITY_VERSION'] = ''
            config.build_settings['ENABLE_BITCODE'] = 'NO'
        end
    end
end
