# Uncomment this line to define a global platform for your project


# Uncomment this line if you're using Swift

use_frameworks!

target 'IMPGeometryTest' do
    platform :osx, '10.11'
    pod 'SnapKit'
    pod 'IMProcessing', :path => '../../'
end

target 'IMPGeometryTestiOS' do
    platform :ios, '8.0'
    pod 'SnapKit'
    pod 'IMProcessing', :path => '../../'
end


post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['DYLIB_COMPATIBILITY_VERSION'] = ''
            config.build_settings['ENABLE_BITCODE'] = 'NO'
        end
    end
end
